### PR TITLE
Fix area selection in screenshot bug

### PR DESCRIPTION
**Pull request by robinhz**
Fix the bug where sometimes the area selection gets into the screenshot.
Method: Inverting the area selection, so that the screenshot area is transparent and the outside is colored

Source code from:
[https://github.com/bdsword/gnome-screenshot/blob/master/src/screenshot-area-selection.c](url)

### CODE REVIEW

**Comment by clefebvre** [comment]
Hi @robinhz is there a bug report for this, was it submitted upstream?

**Comment by robinhz** [comment]
Hi @clefebvre there is a bug report for that:
[https://bugs.launchpad.net/linuxmint/+bug/1285423](url)
I don't know if it was submitted upstream.
Here is another bug report of the same bug in mate:
[https://bugs.launchpad.net/ubuntu/+source/gnome-screenshot/+bug/1406538](url)

**Comment by Sebastiangperez** [comment]
Hi guys , i have  the same issue using Fedora , but i guess this happend when you use it the app is open the first time, then i don't have the issue.

**Comment by ShrirajHegde** [comment]
same on fedora with Nvidia, but happens only with gnome terminal

**Pull request merged**
